use anchor_lang::prelude::*;
use anchor_lang::solana_program;
use anchor_spl::associated_token;
use anchor_spl::token;
use std::convert::TryFrom;

declare_id!("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");

#[derive(Debug)]
#[account]
pub struct EscrowAccount {
    initializer_key: Pubkey,
    initializer_deposit_token_account: Pubkey,
    initializer_receive_token_account: Pubkey,
    initializer_amount: u64,
    taker_amount: u64,
}

pub fn initialize_handler(mut ctx: Context<Initialize>) -> Result<()> {
    let mut initializer = &mut ctx.accounts.initializer;
    let mut escrow_account = &mut ctx.accounts.escrow_account;
    let mut mint = &mut ctx.accounts.mint;
    let mut vault_account = &mut ctx.accounts.vault_account;

    escrow_account.initializer_key = initializer.key();

    Ok(())
}

#[derive(Accounts)]
pub struct Initialize<'info> {
    #[account(mut)]
    pub initializer: Signer<'info>,
    // Generated by Seahorse 
    // #[account(mut)]
    // pub escrow_account: Box<Account<'info, EscrowAccount>>,

    // This is what is needed
    #[account(zero)]
    pub escrow_account: Box<Account<'info, EscrowAccount>>,
    #[account(mut)]
    pub mint: Box<Account<'info, token::Mint>>,
    #[account(
        init,
        payer = initializer,
        seeds = ["token-seed".as_bytes().as_ref()],
        bump,
        token::mint = mint,
        token::authority = initializer
    )]
    pub vault_account: Box<Account<'info, token::TokenAccount>>,
    pub system_program: Program<'info, System>,
    pub token_program: Program<'info, token::Token>,
    pub rent: Sysvar<'info, Rent>,
}

#[program]
pub mod escrow {
    use super::*;

    pub fn initialize(ctx: Context<Initialize>) -> Result<()> {
        initialize_handler(ctx)
    }
}
